### ISSUE TITLE
flowcraft build doesn't throw an error when -o is used incorrectly

### ISSUE THREAD

**Issue by cimendes** [assemblerflow/flowcraft#101]
When the pipeline file name in the -o option of flowcraft build is not included, the .nf file is not created. Despite this, flowcraft didn't throw an error. Here's the command i ran: 

`flowcraft.py build -t "midas_species" -o ~/temp/`

**Comment by ODiogoSilva** [comment]
The bug seems to be actually different. The pipeline should have been created, but `-o ~/temp/` is equivalent to `-o ~/temp`, which generates a `temp.nf` pipeline in the home directory. We should provide a `basename` check to ensure that the path exists AND the pipeline name was provided (and not only the directory by mistake)
